-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "employerId" INT4;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" STRING;

-- CreateTable
CREATE TABLE "Employer" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT4 NOT NULL,
    "company" STRING NOT NULL,
    "website" STRING,

    CONSTRAINT "Employer_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Employer_userId_key" ON "Employer"("userId");

-- CreateIndex
CREATE INDEX "UserEmployerProfile_userId_idx" ON "Employer"("userId");
