-- CreateTable
CREATE TABLE "Admin" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,
    "role" STRING NOT NULL DEFAULT 'admin',

    CONSTRAINT "Admin_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "name" STRING NOT NULL,
    "age" INT4 NOT NULL,
    "password" STRING NOT NULL,
    "country" STRING NOT NULL,
    "state" STRING NOT NULL,
    "city" STRING NOT NULL,
    "language" STRING NOT NULL,
    "specialization" STRING NOT NULL,
    "ndaChecked" BOOL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "JobApplication" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "email" STRING NOT NULL,
    "phone" STRING NOT NULL,
    "address" STRING NOT NULL,
    "linkedin" STRING NOT NULL,
    "github" STRING NOT NULL,
    "coverLetter" STRING NOT NULL,
    "resumeUrl" STRING,
    "jobId" INT4 NOT NULL,
    "userId" INT4 NOT NULL,

    CONSTRAINT "JobApplication_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Job" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "description" STRING NOT NULL,
    "criteria" STRING NOT NULL,
    "skills" STRING NOT NULL,
    "yearsOfExperience" STRING NOT NULL,
    "level" STRING NOT NULL,
    "jobResponsibilities" STRING NOT NULL,
    "location" STRING NOT NULL,
    "salary" STRING NOT NULL,
    "company" STRING NOT NULL,
    "category" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Job_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Admin_email_key" ON "Admin"("email");

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE INDEX "UserJobApplications_userId_idx" ON "JobApplication"("userId");

-- CreateIndex
CREATE INDEX "JobApplications_jobId_idx" ON "JobApplication"("jobId");
