const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const main = async () => {
    try {
        await prisma.job.createMany({
            data: [
                {
                    title: 'Software Engineer',
                    description: 'We are looking for a skilled Software Engineer to join our dynamic team.',
                    criteria: 'Bachelor\'s degree in Computer Science or related field.',
                    skills: 'Proficiency in JavaScript, React, Node.js, and SQL.',
                    yearsOfExperience: '3+ years',
                    level: 'Mid-Senior',
                    jobResponsibilities: 'Develop high-quality software design and architecture, identify, prioritize, and execute tasks in the software development life cycle, and automate tasks through appropriate tools and scripting.',
                    location: 'San Francisco, CA',
                    salary: '$17/hr',
                    company: 'Tech Innovators Inc.',
                    category: 'Software & Data',
                    jobType: 'Full-time',
                    industry: 'Technology'
                },
                {
                    title: 'Product Manager',
                    description: 'Join our product management team to lead the product development lifecycle from ideation to launch.',
                    criteria: 'Bachelor\'s degree in Business or related field.',
                    skills: 'Strong leadership, communication, and project management skills.',
                    yearsOfExperience: '5+ years',
                    level: 'Senior',
                    jobResponsibilities: 'Work closely with engineering, marketing, and sales teams to deliver innovative products, define product vision, roadmap, and growth opportunities, and gather and prioritize product and customer requirements.',
                    location: 'New York, NY',
                    salary: '$14/hr',
                    company: 'Creative Solutions LLC',
                    category: 'Software & Data',
                    jobType: 'Full-time',
                    industry: 'Technology'
                },
                {
                    title: 'Data Scientist',
                    description: 'We are seeking a Data Scientist to analyze large amounts of raw information to find patterns that will help improve our company.',
                    criteria: 'Master\'s degree in Data Science or related field.',
                    skills: 'Experience with Python, R, and machine learning algorithms.',
                    yearsOfExperience: '4+ years',
                    level: 'Mid-Senior',
                    jobResponsibilities: 'Build predictive models and machine-learning algorithms, combine models through ensemble modeling, and present information using data visualization techniques.',
                    location: 'Austin, TX',
                    salary: '$18/hr',
                    company: 'Data Insights Inc.',
                    category: 'Software & Data',
                    jobType: 'Full-time',
                    industry: 'Technology'
                },
                {
                    title: 'Data Evaluator',
                    description: 'We are looking for a Data Evaluator to assess and improve the quality of our datasets.',
                    criteria: 'Bachelor\'s degree in Data Science, Statistics, or related field.',
                    skills: 'Strong analytical skills and attention to detail.',
                    yearsOfExperience: '2+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Evaluate data sets, identify inconsistencies, and provide recommendations for improvements.',
                    location: 'Remote',
                    salary: '$12/hr',
                    company: 'Data Analytics Corp.',
                    category: 'Software & Data',
                    jobType: 'Full-time',
                    industry: 'Technology'
                },
                // Add more jobs to reach up to 40 jobs with the same structure
                {
                    title: 'AI Translation Specialist',
                    description: 'We are looking for an AI Translation Specialist to improve and maintain our translation services.',
                    criteria: 'Bachelor\'s degree in Linguistics or related field.',
                    skills: 'Fluency in multiple languages and experience with AI translation models.',
                    yearsOfExperience: '2+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Develop translation models, evaluate the quality of translations, and provide linguistic expertise to our AI team.',
                    location: 'Remote',
                    salary: '$7/hr',
                    company: 'Global Translations Ltd.',
                    category: 'Translation',
                    jobType: 'Part-time',
                    industry: 'Linguistics'
                },
                {
                    title: 'Bilingual Translator',
                    description: 'Seeking a Bilingual Translator to provide accurate and timely translations of various documents and media.',
                    criteria: 'Bachelor\'s degree in Translation or related field.',
                    skills: 'Fluency in at least two languages and strong writing skills.',
                    yearsOfExperience: '3+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Translate content, ensure cultural relevance, and collaborate with other translators and editors.',
                    location: 'Remote',
                    salary: '$7/hr',
                    company: 'Linguistic Solutions',
                    category: 'Translation',
                    jobType: 'Part-time',
                    industry: 'Linguistics'
                },
                {
                    title: 'Transcriptionist',
                    description: 'We need a detail-oriented Transcriptionist to transcribe audio and video recordings accurately.',
                    criteria: 'High school diploma or equivalent.',
                    skills: 'Excellent listening and typing skills.',
                    yearsOfExperience: '1+ years',
                    level: 'Entry',
                    jobResponsibilities: 'Listen to recordings, type out the content, and ensure the transcriptions are free of errors.',
                    location: 'Remote',
                    salary: '$8/hr',
                    company: 'Accurate Transcripts Inc.',
                    category: 'Transcription',
                    jobType: 'Part-time',
                    industry: 'Linguistics'
                },
                {
                    title: 'Medical Transcriptionist',
                    description: 'Looking for a Medical Transcriptionist to transcribe medical reports from audio recordings.',
                    criteria: 'Certification in Medical Transcription.',
                    skills: 'Knowledge of medical terminology and confidentiality protocols.',
                    yearsOfExperience: '2+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Transcribe medical terminology accurately, ensure confidentiality, and collaborate with healthcare professionals.',
                    location: 'Remote',
                    salary: '$8/hr',
                    company: 'Healthcare Transcription Services',
                    category: 'Transcription',
                    jobType: 'Part-time',
                    industry: 'Healthcare'
                },
                {
                    title: 'Search Engine Evaluator',
                    description: 'Join our team as a Search Engine Evaluator to assess and improve search engine results.',
                    criteria: 'High school diploma or equivalent.',
                    skills: 'Strong analytical skills and attention to detail.',
                    yearsOfExperience: '1+ years',
                    level: 'Entry',
                    jobResponsibilities: 'Analyze search results, provide feedback, and ensure the accuracy and relevance of search engine results.',
                    location: 'Remote',
                    salary: '$10/hr',
                    company: 'Search Quality Inc.',
                    category: 'Search Engine Evaluation',
                    jobType: 'Part-time',
                    industry: 'Technology'
                },
                {
                    title: 'SEO Specialist',
                    description: 'We are seeking an SEO Specialist to optimize our website and improve search engine rankings.',
                    criteria: 'Bachelor\'s degree in Marketing or related field.',
                    skills: 'Experience with SEO tools and techniques.',
                    yearsOfExperience: '3+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Conduct keyword research, optimize website content, and monitor performance using SEO tools.',
                    location: 'Remote',
                    salary: '$15/hr',
                    company: 'Web Marketing LLC',
                    category: 'Search Engine Evaluation',
                    jobType: 'Full-time',
                    industry: 'Marketing'
                },
                {
                    title: 'AI Annotator',
                    description: 'We are seeking an AI Annotator to label and annotate data for machine learning projects.',
                    criteria: 'Bachelor\'s degree in a relevant field.',
                    skills: 'Attention to detail and experience with data annotation tools.',
                    yearsOfExperience: '1+ years',
                    level: 'Entry-Mid',
                    jobResponsibilities: 'Annotate images, videos, and text data, ensure high-quality annotations, and collaborate with the AI team to improve annotation processes.',
                    location: 'Remote',
                    salary: '$11/hr',
                    company: 'AI Solutions Corp.',
                    category: 'AI Annotation',
                    jobType: 'Full-time',
                    industry: 'Technology'
                },
                {
                    title: 'Data Labeler',
                    description: 'Looking for a Data Labeler to provide accurate labels for training machine learning models.',
                    criteria: 'High school diploma or equivalent.',
                    skills: 'Basic computer skills and attention to detail.',
                    yearsOfExperience: '1+ years',
                    level: 'Entry',
                    jobResponsibilities: 'Label data, maintain labeling standards, and work closely with the data science team.',
                    location: 'Remote',
                    salary: '$10/hr',
                    company: 'Data Annotation Services',
                    category: 'AI Annotation',
                    jobType: 'Part-time',
                    industry: 'Technology'
                },
                {
                    title: 'Data Collector',
                    description: 'We are looking for a Data Collector to gather data from various sources for analysis.',
                    criteria: 'High school diploma or equivalent.',
                    skills: 'Basic research skills and attention to detail.',
                    yearsOfExperience: '1+ years',
                    level: 'Entry',
                    jobResponsibilities: 'Collect data from various sources, ensure data accuracy, and organize data for analysis.',
                    location: 'Remote',
                    salary: '$9/hr',
                    company: 'Data Gathering Inc.',
                    category: 'Data Collection',
                    jobType: 'Part-time',
                    industry: 'Research'
                },
                {
                    title: 'Field Data Collector',
                    description: 'We need a Field Data Collector to gather data from different locations for our projects.',
                    criteria: 'High school diploma or equivalent.',
                    skills: 'Strong attention to detail and ability to work independently.',
                    yearsOfExperience: '1+ years',
                    level: 'Entry',
                    jobResponsibilities: 'Travel to various locations, collect data, ensure data accuracy, and report findings.',
                    location: 'Various Locations',
                    salary: '$10/hr',
                    company: 'Field Data Solutions',
                    category: 'Data Collection',
                    jobType: 'Part-time',
                    industry: 'Research'
                },
                {
                    title: 'Customer Support Representative',
                    description: 'We are looking for a Customer Support Representative to provide excellent customer service.',
                    criteria: 'High school diploma or equivalent.',
                    skills: 'Excellent communication and problem-solving skills.',
                    yearsOfExperience: '1+ years',
                    level: 'Entry',
                    jobResponsibilities: 'Assist customers with inquiries, resolve issues, and provide product information.',
                    location: 'Remote',
                    salary: '$12/hr',
                    company: 'Customer Support Inc.',
                    category: 'Customer Support',
                    jobType: 'Full-time',
                    industry: 'Customer Service'
                },
                {
                    title: 'Technical Support Specialist',
                    description: 'Join our team as a Technical Support Specialist to assist customers with technical issues.',
                    criteria: 'Associate\'s degree in IT or related field.',
                    skills: 'Strong technical knowledge and communication skills.',
                    yearsOfExperience: '2+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Provide technical support, troubleshoot issues, and assist customers with product setup.',
                    location: 'Remote',
                    salary: '$14/hr',
                    company: 'Tech Support Services',
                    category: 'Customer Support',
                    jobType: 'Full-time',
                    industry: 'Technology'
                },
                {
                    title: 'Content Writer',
                    description: 'We are seeking a Content Writer to create engaging content for our website and social media.',
                    criteria: 'Bachelor\'s degree in English, Journalism, or related field.',
                    skills: 'Excellent writing and editing skills.',
                    yearsOfExperience: '2+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Write blog posts, create social media content, and collaborate with the marketing team.',
                    location: 'Remote',
                    salary: '$13/hr',
                    company: 'Content Creators LLC',
                    category: 'Content Creation',
                    jobType: 'Full-time',
                    industry: 'Media'
                },
                {
                    title: 'Graphic Designer',
                    description: 'Looking for a Graphic Designer to create visually appealing graphics for our marketing materials.',
                    criteria: 'Bachelor\'s degree in Graphic Design or related field.',
                    skills: 'Proficiency in Adobe Creative Suite and graphic design principles.',
                    yearsOfExperience: '2+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Create graphics for social media, website, and marketing materials.',
                    location: 'Remote',
                    salary: '$14/hr',
                    company: 'Design Studios',
                    category: 'Content Creation',
                    jobType: 'Full-time',
                    industry: 'Media'
                },
                {
                    title: 'Digital Marketing Specialist',
                    description: 'We are looking for a Digital Marketing Specialist to develop and implement digital marketing strategies.',
                    criteria: 'Bachelor\'s degree in Marketing or related field.',
                    skills: 'Experience with SEO, SEM, and social media marketing.',
                    yearsOfExperience: '3+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Create and manage digital marketing campaigns, analyze performance, and optimize strategies.',
                    location: 'Remote',
                    salary: '$15/hr',
                    company: 'Digital Marketing Inc.',
                    category: 'Marketing',
                    jobType: 'Full-time',
                    industry: 'Marketing'
                },
                {
                    title: 'Social Media Manager',
                    description: 'Join our team as a Social Media Manager to oversee our social media presence.',
                    criteria: 'Bachelor\'s degree in Marketing or related field.',
                    skills: 'Experience with social media platforms and content creation.',
                    yearsOfExperience: '2+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Create and manage social media content, engage with followers, and analyze social media performance.',
                    location: 'Remote',
                    salary: '$14/hr',
                    company: 'Social Media Experts',
                    category: 'Marketing',
                    jobType: 'Full-time',
                    industry: 'Marketing'
                },
                {
                    title: 'UX/UI Designer',
                    description: 'We are looking for a UX/UI Designer to create engaging and user-friendly designs for our products.',
                    criteria: 'Bachelor\'s degree in Design or related field.',
                    skills: 'Proficiency in design tools like Figma, Sketch, and Adobe XD.',
                    yearsOfExperience: '3+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Design user interfaces, conduct user research, and create wireframes and prototypes.',
                    location: 'Remote',
                    salary: '$16/hr',
                    company: 'Design Innovations',
                    category: 'Design',
                    jobType: 'Full-time',
                    industry: 'Design'
                },
                {
                    title: 'Marketing Coordinator',
                    description: 'We are looking for a Marketing Coordinator to support our marketing team with various tasks and projects.',
                    criteria: 'Bachelor\'s degree in Marketing or related field.',
                    skills: 'Strong organizational and communication skills.',
                    yearsOfExperience: '2+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Coordinate marketing campaigns, manage social media accounts, and assist with content creation.',
                    location: 'Remote',
                    salary: '$13/hr',
                    company: 'Marketing Solutions Inc.',
                    category: 'Marketing',
                    jobType: 'Full-time',
                    industry: 'Marketing'
                },
                {
                    title: 'Customer Success Manager',
                    description: 'Join our team as a Customer Success Manager to ensure customer satisfaction and retention.',
                    criteria: 'Bachelor\'s degree in Business or related field.',
                    skills: 'Excellent communication and relationship-building skills.',
                    yearsOfExperience: '3+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Manage customer relationships, address customer concerns, and ensure customer success.',
                    location: 'Remote',
                    salary: '$15/hr',
                    company: 'Customer First LLC',
                    category: 'Customer Support',
                    jobType: 'Full-time',
                    industry: 'Customer Service'
                },
                {
                    title: 'Quality Assurance Tester',
                    description: 'We are seeking a Quality Assurance Tester to test our products and ensure they meet the highest standards.',
                    criteria: 'Bachelor\'s degree in Computer Science or related field.',
                    skills: 'Experience with manual and automated testing.',
                    yearsOfExperience: '2+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Develop and execute test plans, report bugs, and collaborate with the development team to resolve issues.',
                    location: 'Remote',
                    salary: '$14/hr',
                    company: 'QA Services Ltd.',
                    category: 'Software & Data',
                    jobType: 'Full-time',
                    industry: 'Technology'
                },
                {
                    title: 'Operations Manager',
                    description: 'We are looking for an Operations Manager to oversee our daily operations and ensure efficiency.',
                    criteria: 'Bachelor\'s degree in Business or related field.',
                    skills: 'Strong leadership and organizational skills.',
                    yearsOfExperience: '5+ years',
                    level: 'Senior',
                    jobResponsibilities: 'Manage operations, develop operational strategies, and ensure compliance with company policies.',
                    location: 'Remote',
                    salary: '$20/hr',
                    company: 'Business Solutions Inc.',
                    category: 'Operations',
                    jobType: 'Full-time',
                    industry: 'Business'
                },
                {
                    title: 'Project Manager',
                    description: 'Join our team as a Project Manager to lead and manage various projects from start to finish.',
                    criteria: 'Bachelor\'s degree in Project Management or related field.',
                    skills: 'Strong leadership, communication, and project management skills.',
                    yearsOfExperience: '4+ years',
                    level: 'Mid-Senior',
                    jobResponsibilities: 'Define project scope, manage project timelines, and ensure successful project delivery.',
                    location: 'Remote',
                    salary: '$18/hr',
                    company: 'Project Leaders LLC',
                    category: 'Project Management',
                    jobType: 'Full-time',
                    industry: 'Management'
                },
                {
                    title: 'HR Specialist',
                    description: 'We are seeking an HR Specialist to manage our human resources operations and support our employees.',
                    criteria: 'Bachelor\'s degree in Human Resources or related field.',
                    skills: 'Strong communication and interpersonal skills.',
                    yearsOfExperience: '3+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Manage employee relations, handle recruitment, and ensure compliance with HR policies.',
                    location: 'Remote',
                    salary: '$15/hr',
                    company: 'HR Solutions Ltd.',
                    category: 'Human Resources',
                    jobType: 'Full-time',
                    industry: 'Human Resources'
                },
                {
                    title: 'Accountant',
                    description: 'Looking for an Accountant to manage our financial records and ensure accuracy.',
                    criteria: 'Bachelor\'s degree in Accounting or related field.',
                    skills: 'Proficiency in accounting software and strong analytical skills.',
                    yearsOfExperience: '3+ years',
                    level: 'Mid',
                    jobResponsibilities: 'Manage financial records, prepare financial reports, and ensure compliance with accounting standards.',
                    location: 'Remote',
                    salary: '$16/hr',
                    company: 'Accounting Services Inc.',
                    category: 'Finance',
                    jobType: 'Full-time',
                    industry: 'Finance'
                },
                {
                    title: 'Administrative Assistant',
                    description: 'We are looking for an Administrative Assistant to provide administrative support to our team.',
                    criteria: 'High school diploma or equivalent.',
                    skills: 'Strong organizational and communication skills.',
                    yearsOfExperience: '1+ years',
                    level: 'Entry',
                    jobResponsibilities: 'Manage schedules, handle correspondence, and provide administrative support.',
                    location: 'Remote',
                    salary: '$12/hr',
                    company: 'Admin Support LLC',
                    category: 'Administration',
                    jobType: 'Full-time',
                    industry: 'Administration'
                }
            ],
        });
        console.log('Job data seeded successfully.');
    } catch (error) {
        console.error('Error seeding job data:', error);
    } finally {
        await prisma.$disconnect();
    }
};

main()
    .catch((e) => {
        console.error('Error in main function:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
